### ISSUE TITLE
Roots is moving towards framework-agnosticism

### ISSUE THREAD

**Issue by mAAdhaTTah** [schikulski/gromf#16]
As per [this issue](https://github.com/roots/roots/issues/1110#issuecomment-52338320). Just want to make you aware - after they implement this, we may want to consider transitioning Gromf towards a Foundation-specific plugin; I'm sure we can take a lot of the work we did and just bundle the Foundation stuff.. I believe they've already pulled out some of Bootstrap styling in the markup.

**Comment by schikulski** [comment]
Working on a Sage 8.x version of Gromf now

**Comment by Leland** [comment]
@schikulski Exciting!
