### ISSUE TITLE
Pagination in Gromf

### ISSUE THREAD

**Issue by nusserstudios** [schikulski/gromf#25]
What is the best way to achieve pagination for custom post types?

**Comment by mAAdhaTTah** [comment]
Does it not work by default? Works for me here: http://jamesdigioia.com/gistpens/page/2/

**Comment by nusserstudios** [comment]
It does using the index, but not a page template. Ive tried adding it from the index, but I get a 404 if I try to go to it.

**Comment by nusserstudios** [comment]
Doh, I think I found what I was wanting to do! http://discourse.roots.io/t/how-to-create-next-prev-like-the-one-in-roots-index-php-instead/590/5

Thanks James
