### ISSUE TITLE
Interchange Header Image Not Working?

### ISSUE THREAD

**Issue by mAAdhaTTah** [schikulski/gromf#26]
So I know this isn't related to gromf exactly, but it's the base of my theme and I'm having a Foundation issue, so maybe you can help me out? The splash on my homepage: http://jamesdigioia.com/ doesn't swap out the small, medium and large images, despite being marked up for Interchange and background images:

```php
<header id="splash" data-stellar-background-ratio=".5" data-interchange="
    [http://jamesdigioia.com/app/themes/socialwindow/assets/img_min/header-large.jpg, (large-only)],
    [http://jamesdigioia.com/app/themes/socialwindow/assets/img_min/header-medium.jpg, (medium-only)],
    [http://jamesdigioia.com/app/themes/socialwindow/assets/img_min/header-small.jpg, (small-only)],
    [http://jamesdigioia.com/app/themes/socialwindow/assets/img_min/header.jpg, (default)]
">
```

http://foundation.zurb.com/docs/components/interchange.html

What am I doing wrong?

**Comment by nusserstudios** [comment]
You could just drop interchange and just use different background images with media queries. That's what I've done just bypassing interchange. I have ran into this same issue myself. I also just use custom fields and visibility classes to pass different images. Wish I could help out more, but I've ran into the same thing trying to use interchange. Hope this helps.

**Comment by mAAdhaTTah** [comment]
That may be a way of going about it, but I'd have to add the css inline if I want to make the header swappable (which I will eventually - right now it's just my site but I do want to "universalize" it).

**Comment by mAAdhaTTah** [comment]
I opened an issue @ Foundation: https://github.com/zurb/foundation/issues/6218 but if you or @schikulski have any ideas, let me know!

**Comment by mAAdhaTTah** [comment]
They fixed it. Apparently, Interchange matches the *last matching rule*, which in my case was (default). I think they might have an issue with using the `-only` queries, but I got it working anyway. Thanks!
