### ISSUE TITLE
How do I import _settings ? 

### ISSUE THREAD

**Issue by khejduk** [schikulski/Gromf#27]
Why did the location of Foundation Setings change? How do I import it?

**Comment by schikulski** [comment]
I simply overwrite the variables i need to overwrite in [main.scss](https://github.com/schikulski/Gromf/blob/master/assets/styles/main.scss). The settings file are still in the bower_components folder, so you can easily copy/paste variables from there. It's no big deal to put it in the assets folder, and include it in main.scss before foundation itself, but I think it's cleaner like this. I'm always open for suggestions though.

**Comment by khejduk** [comment]
I am okay with that, I just edited the file in the bower_components folder. I guess I just did not feel it was necessary to move the file from the assets dir, but maybe that is just because it is what I am used to and it has become a standard part of my work process.

**Comment by mAAdhaTTah** [comment]
Don't edit the files in bower_components, or every time you update those files with bower, your changes will be overwritten.

**Comment by khejduk** [comment]
Yes, I actually knew this.. I do this once in a while and then remember once it gets updated/overwritten. I will just copy and paste variables, but I still think its easier to just have that file right there. There are already a dozen other .scss files, what is one more? Thanks

**Comment by Leland** [comment]
If you want the entire array of settings, you could just copy/paste the contents of the Bower-imported file into the _variables file. The problem with having the settings file in this repo itself is that it's an external dependency that would now be tracked here.

**Comment by khejduk** [comment]
Again, this just sounds like more work. It used to be right there for you
to edit instead of having to copy and paste variables back-and-forth.

On Tuesday, July 28, 2015, Leland Clemmons <notifications@github.com> wrote:

> If you want the entire array of settings, you could just copy/paste the
> contents of the Bower-imported file into the _variables file. The problem
> with having the settings file in this repo itself is that it's an external
> dependency that would now be tracked here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/schikulski/Gromf/issues/27#issuecomment-125775589>.
>


-- 
*Kevin Hejduk*

**Comment by schikulski** [comment]
I have to agree with @mAAdhaTTah that editing files in bower_components(outside the repository) sounds like a bad idea, and what @Leland says about having an external dependency file in the repo is not really maintainable either.
