### ISSUE TITLE
Changing Zurb default styles not outputting while gulp watch is running

### ISSUE THREAD

**Issue by ayezee33** [schikulski/Gromf#29]
Perhaps this isn't the proper way to make changes to the sass files but whenever I go to bower_components/foundation/foundation/_settings.scss and make a change I need to run GULP for the changes to take place....could it be a simple change to the gulpfile to also watch that directory?

Or is it a better practice to override all Zurb styles in a custom.scss file? Seems like it would cause more code then necessary. Any help/guidance here would be awesome.

**Comment by mAAdhaTTah** [comment]
> Or is it a better practice to override all Zurb styles in a custom.scss file?

It is better practice; bower_components shouldn't be committed, so if you're making changes in there, they'll be overridden when you do `bower install` again, should you add additional dependencies.

**Comment by nusserstudios** [comment]
I just copy the _settings.scss from bower_components and place it in my styles and add it right into the styles directory and edit main.scss to add @import "settings";
