### ISSUE TITLE
How do I add dropdown support to the new nav walker?

### ISSUE THREAD

**Issue by khejduk** [schikulski/gromf#33]
Now that the nav walker is in Soil, how do I add top-bar support back in?

**Comment by nusserstudios** [comment]
Did you ever figure it out?

1. Head to your lib folder and create a new file called nav.php and drop this code in from the link below.
https://gist.github.com/nusserstudios/904d13b91fcc541472c2

2. Update your functions.php file to include this:
  'lib/nav.php'                  	// Foundation Topbar Navigation

3. Update the header.php file to look like this:
https://gist.github.com/nusserstudios/eaf1801d14a2d959ee2d

**Comment by nusserstudios** [comment]
Make sure you have the Soil Plugin activated as well.

**Comment by khejduk** [comment]
Thanks.. I have figured this out.

*Kevin Hejduk*
